package com.example.turisticka_agencija.model;

public enum Role {
    CUSTOMER,
    ADMIN,
    SALES_AGENT,
    MANAGER,
    GUIDE,
    DIRECTOR,

    COMPLAINT_OPERATOR,
    COMPLAINT_MANAGER,
    COMPLAINT_TEAM_ACCOMMODATION,
    COMPLAINT_TEAM_TRANSPORT,
    COMPLAINT_TEAM_DOCUMENTATION,
    COMPLAINT_TEAM_OTHER
}