spring.application.name=turisticka-agencija
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/turisticka_agencija
spring.datasource.username=postgres
spring.datasource.password=lozinka123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luxtravel.agencija@gmail.com
spring.mail.password=frpn yspv eajy wltr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true