spring.application.name=turisticka-agencija
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/turisticka_agencija
spring.datasource.username=postgres
spring.datasource.password=lozinka123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
